// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMkLkkGS-GTLvwWpjrnkghZF449cv7-DI',
    appId: '1:978597517356:web:7ef5581c87e50095919989',
    messagingSenderId: '978597517356',
    projectId: 'pocketpact-58398',
    authDomain: 'pocketpact-58398.firebaseapp.com',
    storageBucket: 'pocketpact-58398.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF5vuv59wDAqGu2xboP1uG5b0Lw14ETxA',
    appId: '1:978597517356:android:b23a45718685df06919989',
    messagingSenderId: '978597517356',
    projectId: 'pocketpact-58398',
    storageBucket: 'pocketpact-58398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGCj4GSWVEuANoag2zkE65vd9qtaS-I6c',
    appId: '1:978597517356:ios:1142e5d383435ec1919989',
    messagingSenderId: '978597517356',
    projectId: 'pocketpact-58398',
    storageBucket: 'pocketpact-58398.firebasestorage.app',
    iosBundleId: 'com.example.pocketPact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGCj4GSWVEuANoag2zkE65vd9qtaS-I6c',
    appId: '1:978597517356:ios:1142e5d383435ec1919989',
    messagingSenderId: '978597517356',
    projectId: 'pocketpact-58398',
    storageBucket: 'pocketpact-58398.firebasestorage.app',
    iosBundleId: 'com.example.pocketPact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMkLkkGS-GTLvwWpjrnkghZF449cv7-DI',
    appId: '1:978597517356:web:97a3a1b49d66885a919989',
    messagingSenderId: '978597517356',
    projectId: 'pocketpact-58398',
    authDomain: 'pocketpact-58398.firebaseapp.com',
    storageBucket: 'pocketpact-58398.firebasestorage.app',
  );
}
